import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
const migration = await readFile(
  new URL("../migrations/20260921_lager_iphone.sql", import.meta.url),
  "utf8",
);
const admin = "00000000-0000-4000-8000-000000000001",
  employee = "00000000-0000-4000-8000-000000000002",
  outsider = "00000000-0000-4000-8000-000000000003";
async function fixture() {
  const db = new PGlite();
  await db.exec(`
 create role anon;create role authenticated;create schema auth;
 create table auth.users(id uuid primary key,email text);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 create table public.phones(id bigint generated by default as identity primary key,model text not null,storage_gb integer not null,color text,battery_health integer,condition text,status text,purchase_price numeric not null,repair_cost numeric not null,other_cost numeric not null,selling_price numeric,purchase_source text,notes text,created_at timestamptz default now());
 create table public.market_prices(id uuid primary key default gen_random_uuid(),model text,storage_gb integer,condition text,source text,market_price numeric,listing_url text,created_at timestamptz default now());
 insert into public.phones(model,storage_gb,status,purchase_price,repair_cost,other_cost,selling_price,notes) values ('Legacy iPhone',128,'Sold',100,20,30,200,'Keep this record');
 insert into public.market_prices(model,storage_gb,condition,source,market_price) values ('Legacy iPhone',128,'Good','Tradera',1000);
 insert into auth.users values ('${admin}','admin@example.com'),('${employee}','employee@example.com'),('${outsider}','outsider@example.com');
 grant all on public.phones,public.market_prices to anon,authenticated;
 grant select(purchase_price) on public.phones to authenticated;
 `);
  return db;
}
async function identity(db, id) {
  await db.exec("reset role");
  await db.query("select set_config('request.jwt.claim.sub',$1,false)", [id]);
  await db.exec("set role authenticated");
}
test("migration preserves legacy rows, is repeatable, and enforces database permissions", async () => {
  const db = await fixture();
  try {
    const before = (await db.query("select * from phones")).rows[0];
    await db.exec(migration);
    await db.exec(migration);
    const after = (await db.query("select * from phones")).rows[0];
    assert.deepEqual(
      { ...after, imei: undefined },
      { ...before, imei: undefined },
    );
    assert.equal(
      (await db.query("select count(*)::int n from market_prices")).rows[0].n,
      1,
    );
    await db.query(
      "insert into lager_memberships values ($1,'admin',true,true),($2,'employee',false,false)",
      [admin, employee],
    );
    await identity(db, employee);
    await assert.rejects(
      db.query("select purchase_price from phones"),
      /permission denied/i,
    );
    const snapshot = (await db.query("select lager_dashboard() d")).rows[0].d;
    assert.equal(snapshot.phones[0].notes, "Keep this record");
    assert.equal(Object.hasOwn(snapshot.phones[0], "purchase_price"), false);
    await assert.rejects(
      db.query("select lager_save_phone('1', '{\"purchase_price\":0}'::jsonb)"),
      /not permitted/,
    );
    await assert.rejects(
      db.query("select lager_delete_phone('1')"),
      /restricted/,
    );
    await assert.rejects(
      db.query(
        "select lager_set_member('employee@example.com','admin',true,true)",
      ),
      /Admin access/,
    );
    await db.query(
      "select lager_save_phone('1', '{\"color\":\"Blue\"}'::jsonb)",
    );
    await db.query(
      'select lager_save_phone(null, \'{"model":"New phone","storage_gb":256,"imei":"001234567890123"}\'::jsonb)',
    );
    await identity(db, admin);
    let full = (await db.query("select lager_dashboard() d")).rows[0].d;
    assert.equal(full.phones.find((p) => p.id === 1).purchase_price, 100);
    assert.equal(full.phones.find((p) => p.id === 2).imei, "001234567890123");
    await db.query(
      'select lager_save_phone(\'2\',\'{"status":"Sold","purchase_price":400,"selling_price":700}\'::jsonb)',
    );
    await db.query(
      'select lager_add_market(\'{"model":"New phone","storage_gb":256,"condition":"Good","source":"Blocket","market_price":900,"listing_url":"https://example.com/item"}\'::jsonb)',
    );
    await assert.rejects(
      db.query(
        'select lager_add_market(\'{"model":"X","storage_gb":128,"condition":"Good","source":"Other","market_price":1,"listing_url":"javascript:alert(1)"}\'::jsonb)',
      ),
      /URL/,
    );
    await db.query(
      "select lager_set_member('employee@example.com','employee',true,true)",
    );
    await identity(db, employee);
    full = (await db.query("select lager_dashboard() d")).rows[0].d;
    assert.equal(full.phones.find((p) => p.id === 2).status, "Sold");
    assert.equal(full.phones.find((p) => p.id === 2).purchase_price, 400);
    await db.query("select lager_delete_phone('2')");
    await identity(db, outsider);
    await assert.rejects(db.query("select lager_dashboard()"), /assignment/);
    await db.exec("reset role;set role anon");
    await assert.rejects(
      db.query("select lager_dashboard()"),
      /permission denied/,
    );
  } finally {
    await db.close();
  }
});
test("unknown required columns cause migration to roll back safely", async () => {
  const db = await fixture();
  try {
    await db.exec(
      "alter table market_prices add column required_external text not null default 'existing';alter table market_prices alter column required_external drop default;",
    );
    await assert.rejects(
      db.exec(migration),
      /Required columns without defaults/,
    );
    await db.exec("rollback");
    assert.equal(
      (await db.query("select count(*)::int n from phones")).rows[0].n,
      1,
    );
    assert.equal(
      (
        await db.query(
          "select count(*)::int n from information_schema.columns where table_name='phones' and column_name='imei'",
        )
      ).rows[0].n,
      0,
    );
  } finally {
    await db.close();
  }
});
