-- Additive Lager iPhone upgrade. Existing rows become business inventory by default.
-- This migration never deletes or rewrites existing phone, price, user or auth rows.
begin;

alter table public.phones add column if not exists grade text;
alter table public.phones add column if not exists inventory_scope text not null default 'business';
alter table public.phones add column if not exists purchase_date date;
alter table public.phones add column if not exists updated_at timestamptz not null default now();
do $$ begin
 if exists(select 1 from public.phones where inventory_scope not in ('business','samer')) then
  raise exception 'Unknown inventory scope found; no changes applied';
 end if;
end $$;
alter table public.phones drop constraint if exists phones_inventory_scope_check;
alter table public.phones add constraint phones_inventory_scope_check check(inventory_scope in ('business','samer')) not valid;
alter table public.phones validate constraint phones_inventory_scope_check;

create table if not exists public.lager_sale_history (
 id bigint generated by default as identity primary key,
 phone_id text not null,
 inventory_scope text not null check(inventory_scope in ('business','samer')),
 model text not null,
 storage_gb integer,
 grade text,
 condition text,
 purchase_price numeric not null default 0,
 repair_cost numeric not null default 0,
 other_cost numeric not null default 0,
 selling_price numeric not null default 0,
 realized_profit numeric not null default 0,
 sold_at timestamptz not null default now(),
 returned_at timestamptz,
 sold_by uuid references auth.users(id)
);
alter table public.lager_sale_history enable row level security;
revoke all on public.lager_sale_history from public,anon,authenticated;

create or replace function public.lager_dashboard() returns jsonb
language plpgsql security definer set search_path='' as $$
declare a jsonb:=public.lager_access(); p jsonb; m jsonb; h jsonb;
begin
 select coalesce(jsonb_agg(visible order by created_at desc),'[]'::jsonb) into p from (
 select ph.created_at,
 (select jsonb_object_agg(key,value) from jsonb_each(to_jsonb(ph)) where key=any(
 array['id','model','storage_gb','color','grade','battery_health','condition','imei','status','selling_price','purchase_source','purchase_date','notes','inventory_scope','created_at','updated_at'] ||
 case when (a->>'can_view_financials')::boolean then array['purchase_price','repair_cost','other_cost'] else array[]::text[] end)) visible
 from public.phones ph) rows;
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'model',model,'storage_gb',storage_gb,'condition',condition,'source',source,'market_price',market_price,'listing_url',listing_url) order by created_at desc),'[]'::jsonb) into m from public.market_prices;
 select case when (a->>'can_view_financials')::boolean then coalesce(jsonb_agg(to_jsonb(sh) order by sold_at desc),'[]'::jsonb) else '[]'::jsonb end into h from public.lager_sale_history sh where inventory_scope='business';
 return jsonb_build_object('access',a,'phones',p,'market_prices',m,'sale_history',h);
end $$;

create or replace function public.lager_save_phone(phone_id text,payload jsonb) returns void
language plpgsql security definer set search_path='' as $$
declare a jsonb:=public.lager_access(); k text; cols text; vals text; changes text; previous jsonb; n integer;
 allowed text[]:=array['model','storage_gb','color','grade','battery_health','condition','imei','status','selling_price','purchase_source','purchase_date','notes','inventory_scope'];
begin
 if (a->>'can_view_financials')::boolean then allowed:=allowed||array['purchase_price','repair_cost','other_cost']; end if;
 if payload is null or jsonb_typeof(payload)<>'object' or payload='{}'::jsonb then raise exception 'Phone information is required'; end if;
 if phone_id is not null then select to_jsonb(p) into previous from public.phones p where id::text=phone_id for update; if not found then raise exception 'Phone no longer exists. Refresh inventory.'; end if; end if;
 for k in select jsonb_object_keys(payload) loop
  if not k=any(allowed) then raise exception 'Field is not permitted: %',k using errcode='42501'; end if;
  if previous is not null and payload->k=previous->k then continue; end if;
  if k='model' and coalesce(length(btrim(payload->>k)),0)=0 then raise exception 'Model is required'; end if;
  if k='storage_gb' and (payload->>k is null or (payload->>k)::numeric<=0 or (payload->>k)::numeric<>trunc((payload->>k)::numeric)) then raise exception 'Storage must be a positive whole number'; end if;
  if k in ('purchase_price','repair_cost','other_cost','selling_price') and (payload->>k is null or (payload->>k)::numeric<0 or (payload->>k) in ('NaN','Infinity','-Infinity')) then raise exception 'Prices and costs must be nonnegative numbers'; end if;
  if k='battery_health' and payload->>k is not null and ((payload->>k)::numeric not between 0 and 100 or (payload->>k)::numeric<>trunc((payload->>k)::numeric)) then raise exception 'Battery health must be a whole percentage between 0 and 100'; end if;
  if k='imei' and coalesce(payload->>k,'')<>'' and (payload->>k)!~'^[0-9]{15}$' then raise exception 'IMEI must contain 15 digits or be blank'; end if;
  if k='status' and coalesce(payload->>k,'') not in ('In Stock','Repairing','Listed','Sold') then raise exception 'Invalid phone status'; end if;
  if k='condition' and coalesce(payload->>k,'') not in ('Excellent','Good','Fair','Damaged') then raise exception 'Invalid condition'; end if;
  if k='inventory_scope' and coalesce(payload->>k,'') not in ('business','samer') then raise exception 'Invalid inventory scope'; end if;
  if k='grade' and length(coalesce(payload->>k,''))>30 then raise exception 'Grade is too long'; end if;
 end loop;
 if phone_id is null then
  if coalesce(length(btrim(payload->>'model')),0)=0 or not payload?'storage_gb' then raise exception 'Model and storage are required'; end if;
  payload:=jsonb_build_object('purchase_price',0,'repair_cost',0,'other_cost',0,'selling_price',0,'status','In Stock','condition','Good','inventory_scope','business')||payload;
  if exists(select 1 from information_schema.columns where table_schema='public' and table_name='phones' and column_name='user_id') then payload:=payload||jsonb_build_object('user_id',auth.uid()); end if;
  select string_agg(format('%I',key),','),string_agg(format('r.%I',key),',') into cols,vals from jsonb_object_keys(payload) key;
  execute format('insert into public.phones (%s) select %s from jsonb_populate_record(null::public.phones,$1) r',cols,vals) using payload;
 else
  payload:=payload||jsonb_build_object('updated_at',now());
  select string_agg(format('%I=r.%I',key,key),',') into changes from jsonb_object_keys(payload) key;
  execute format('update public.phones p set %s from jsonb_populate_record(null::public.phones,$1) r where p.id::text=$2',changes) using payload,phone_id;
  get diagnostics n=row_count; if n<>1 then raise exception 'Expected exactly one phone to update'; end if;
 end if;
end $$;

create or replace function public.lager_transition_phone(phone_id text,new_status text) returns void
language plpgsql security definer set search_path='' as $$
declare a jsonb:=public.lager_access(); p public.phones; n integer;
begin
 if new_status not in ('Sold','In Stock') then raise exception 'Invalid transition'; end if;
 select * into p from public.phones where id::text=phone_id for update;
 if not found then raise exception 'Phone no longer exists'; end if;
 if new_status='Sold' then
  if p.status='Sold' then raise exception 'Phone is already sold'; end if;
  insert into public.lager_sale_history(phone_id,inventory_scope,model,storage_gb,grade,condition,purchase_price,repair_cost,other_cost,selling_price,realized_profit,sold_by)
  values(p.id::text,p.inventory_scope,p.model,p.storage_gb,p.grade,p.condition,coalesce(p.purchase_price,0),coalesce(p.repair_cost,0),coalesce(p.other_cost,0),coalesce(p.selling_price,0),coalesce(p.selling_price,0)-coalesce(p.purchase_price,0)-coalesce(p.repair_cost,0)-coalesce(p.other_cost,0),auth.uid());
 else
  if p.status<>'Sold' then raise exception 'Only a sold phone can return to stock'; end if;
  update public.lager_sale_history set returned_at=now() where id=(select sh.id from public.lager_sale_history sh where sh.phone_id=p.id::text and sh.returned_at is null order by sh.sold_at desc limit 1);
 end if;
 update public.phones set status=new_status,updated_at=now() where id=p.id;
end $$;

do $$ declare f regprocedure; begin
 for f in select p.oid::regprocedure from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in ('lager_dashboard','lager_save_phone','lager_transition_phone') loop
  execute format('revoke all on function %s from public,anon,authenticated',f);
  execute format('grant execute on function %s to authenticated',f);
 end loop;
end $$;
notify pgrst,'reload schema';
commit;
