-- Production adoption layer: cloud audit, snapshots, customer sale metadata and warranty tracking.
begin;

create table if not exists public.lager_activity_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  phone_id text,
  phone_label text,
  detail text,
  metadata jsonb not null default '{}'::jsonb
);
alter table public.lager_activity_log enable row level security;
revoke all on public.lager_activity_log from public, anon, authenticated;

create table if not exists public.lager_cloud_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default current_date unique,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  data jsonb not null
);
alter table public.lager_cloud_snapshots enable row level security;
revoke all on public.lager_cloud_snapshots from public, anon, authenticated;

alter table public.lager_sale_history add column if not exists buyer_name text;
alter table public.lager_sale_history add column if not exists buyer_contact text;
alter table public.lager_sale_history add column if not exists payment text;
alter table public.lager_sale_history add column if not exists sales_channel text;
alter table public.lager_sale_history add column if not exists order_ref text;
alter table public.lager_sale_history add column if not exists warranty_months integer;
alter table public.lager_sale_history add column if not exists warranty_until date;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.lager_snapshot_internal(snapshot_actor uuid default null)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare new_id bigint;
begin
  insert into public.lager_cloud_snapshots(snapshot_date, created_by, data)
  values (
    current_date,
    snapshot_actor,
    jsonb_build_object(
      'version', 1,
      'created_at', now(),
      'phones', coalesce((select jsonb_agg(to_jsonb(p) order by p.id) from public.phones p), '[]'::jsonb),
      'sale_history', coalesce((select jsonb_agg(to_jsonb(s) order by s.id) from public.lager_sale_history s), '[]'::jsonb),
      'market_prices', coalesce((select jsonb_agg(to_jsonb(m) order by m.id) from public.market_prices m), '[]'::jsonb)
    )
  )
  on conflict (snapshot_date) do update
  set created_at=excluded.created_at, created_by=excluded.created_by, data=excluded.data
  returning id into new_id;

  delete from public.lager_cloud_snapshots
  where snapshot_date < current_date - 60;

  return new_id;
end
$$;

revoke all on function private.lager_snapshot_internal(uuid) from public, anon, authenticated;

create or replace function public.lager_log_activity(
  action_name text,
  phone_id text default null,
  phone_label text default null,
  detail text default null,
  metadata jsonb default '{}'::jsonb
) returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  perform public.lager_access();
  if coalesce(length(btrim(action_name)),0)=0 then
    raise exception 'Action is required';
  end if;
  insert into public.lager_activity_log(actor_id, action, phone_id, phone_label, detail, metadata)
  values (
    auth.uid(),
    left(action_name,120),
    nullif(left(coalesce(phone_id,''),120),''),
    nullif(left(coalesce(phone_label,''),240),''),
    nullif(left(coalesce(detail,''),1000),''),
    coalesce(metadata,'{}'::jsonb)
  );
end
$$;

create or replace function public.lager_activity(limit_count integer default 150)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare result jsonb;
begin
  perform public.lager_access();
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', x.id,
        'at', x.occurred_at,
        'action', x.action,
        'phoneId', x.phone_id,
        'phone', x.phone_label,
        'detail', x.detail,
        'actor', x.actor_email
      )
      order by x.occurred_at desc
    ),
    '[]'::jsonb
  ) into result
  from (
    select l.*, u.email as actor_email
    from public.lager_activity_log l
    left join auth.users u on u.id=l.actor_id
    order by l.occurred_at desc
    limit greatest(1, least(coalesce(limit_count,150),500))
  ) x;
  return result;
end
$$;

create or replace function public.lager_create_snapshot()
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare snapshot_id bigint; created timestamptz;
begin
  perform public.lager_access();
  snapshot_id := private.lager_snapshot_internal(auth.uid());
  select created_at into created from public.lager_cloud_snapshots where id=snapshot_id;
  insert into public.lager_activity_log(actor_id, action, phone_label, detail)
  values(auth.uid(),'Cloud backup created','System','Daily inventory snapshot saved in Supabase.');
  return jsonb_build_object('id',snapshot_id,'created_at',created);
end
$$;

create or replace function public.lager_snapshot_status()
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare latest public.lager_cloud_snapshots; total integer;
begin
  perform public.lager_access();
  select * into latest from public.lager_cloud_snapshots order by created_at desc limit 1;
  select count(*) into total from public.lager_cloud_snapshots;
  return jsonb_build_object(
    'count', total,
    'last_created_at', latest.created_at,
    'last_snapshot_date', latest.snapshot_date
  );
end
$$;

create or replace function public.lager_complete_sale(phone_id text, sale_meta jsonb default '{}'::jsonb)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  a jsonb:=public.lager_access();
  p public.phones;
  final_price numeric;
  months integer;
  sold_date date:=current_date;
begin
  if not (a->>'can_view_financials')::boolean then
    raise exception 'Financial access required' using errcode='42501';
  end if;
  select * into p from public.phones where id::text=phone_id for update;
  if not found then raise exception 'Phone no longer exists'; end if;
  if p.status='Sold' then raise exception 'Phone is already sold'; end if;

  final_price:=coalesce(nullif(sale_meta->>'price','')::numeric,p.selling_price,0);
  if final_price<=0 then raise exception 'Final selling price is required'; end if;
  months:=coalesce(nullif(sale_meta->>'warrantyMonths','')::integer,3);
  if months<0 or months>36 then raise exception 'Warranty must be between 0 and 36 months'; end if;

  update public.phones
  set selling_price=final_price,status='Sold',updated_at=now()
  where id=p.id;

  insert into public.lager_sale_history(
    phone_id,inventory_scope,model,storage_gb,grade,condition,
    purchase_price,repair_cost,other_cost,selling_price,realized_profit,sold_by,
    buyer_name,buyer_contact,payment,sales_channel,order_ref,warranty_months,warranty_until
  ) values (
    p.id::text,p.inventory_scope,p.model,p.storage_gb,p.grade,p.condition,
    coalesce(p.purchase_price,0),coalesce(p.repair_cost,0),coalesce(p.other_cost,0),
    final_price,
    final_price-coalesce(p.purchase_price,0)-coalesce(p.repair_cost,0)-coalesce(p.other_cost,0),
    auth.uid(),
    nullif(left(coalesce(sale_meta->>'buyer',''),200),''),
    nullif(left(coalesce(sale_meta->>'contact',''),240),''),
    nullif(left(coalesce(sale_meta->>'payment',''),80),''),
    nullif(left(coalesce(sale_meta->>'channel',''),80),''),
    nullif(left(coalesce(sale_meta->>'orderRef',''),160),''),
    months,
    case when months>0 then sold_date + make_interval(months=>months) else sold_date end
  );

  insert into public.lager_activity_log(actor_id,action,phone_id,phone_label,detail)
  values(
    auth.uid(),'Phone sold',p.id::text,
    concat_ws(' ',p.model,case when p.storage_gb is not null then p.storage_gb||'GB' end),
    concat(final_price,' SEK · ',coalesce(sale_meta->>'channel','Direct'),' · Warranty ',months,' month(s)')
  );
end
$$;

do $$
declare f regprocedure;
begin
  for f in
    select p.oid::regprocedure
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public'
      and p.proname in ('lager_log_activity','lager_activity','lager_create_snapshot','lager_snapshot_status','lager_complete_sale')
  loop
    execute format('revoke all on function %s from public,anon,authenticated',f);
    execute format('grant execute on function %s to authenticated',f);
  end loop;
end $$;

create extension if not exists pg_cron with schema pg_catalog;
do $$
begin
  if not exists(select 1 from cron.job where jobname='lager_daily_snapshot') then
    perform cron.schedule(
      'lager_daily_snapshot',
      '17 2 * * *',
      'select private.lager_snapshot_internal(null);'
    );
  end if;
end $$;

notify pgrst,'reload schema';
commit;