create table if not exists public.spare_parts (
  id bigint generated by default as identity primary key,
  device_model text not null,
  part_type text not null,
  quality text not null default 'New',
  color text,
  quantity integer not null default 1,
  unit_cost numeric not null default 0,
  storage_location text,
  supplier text,
  notes text,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint spare_parts_quantity_check check (quantity >= 0 and quantity <= 9999),
  constraint spare_parts_unit_cost_check check (unit_cost >= 0),
  constraint spare_parts_device_model_check check (char_length(btrim(device_model)) between 1 and 120),
  constraint spare_parts_part_type_check check (char_length(btrim(part_type)) between 1 and 120)
);

alter table public.spare_parts enable row level security;
revoke all on table public.spare_parts from public, anon, authenticated;
revoke all on sequence public.spare_parts_id_seq from public, anon, authenticated;

create index if not exists spare_parts_device_model_idx on public.spare_parts (lower(device_model));
create index if not exists spare_parts_part_type_idx on public.spare_parts (lower(part_type));
create index if not exists spare_parts_updated_at_idx on public.spare_parts (updated_at desc);

create or replace function public.lager_parts()
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  a jsonb:=public.lager_access();
  result jsonb;
begin
  select coalesce(
    jsonb_agg(
      jsonb_strip_nulls(
        jsonb_build_object(
          'id', p.id,
          'device_model', p.device_model,
          'part_type', p.part_type,
          'quality', p.quality,
          'color', p.color,
          'quantity', p.quantity,
          'unit_cost', case when (a->>'can_view_financials')::boolean then p.unit_cost else null end,
          'storage_location', p.storage_location,
          'supplier', p.supplier,
          'notes', p.notes,
          'created_at', p.created_at,
          'updated_at', p.updated_at
        )
      )
      order by p.updated_at desc, p.id desc
    ),
    '[]'::jsonb
  )
  into result
  from public.spare_parts p;

  return result;
end
$$;

create or replace function public.lager_save_part(part_id text, payload jsonb)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  a jsonb:=public.lager_access();
  existing public.spare_parts;
  v_model text;
  v_type text;
  v_quality text;
  v_color text;
  v_quantity integer;
  v_unit_cost numeric;
  v_location text;
  v_supplier text;
  v_notes text;
begin
  if payload is null or jsonb_typeof(payload) <> 'object' then
    raise exception 'Part information is required';
  end if;

  v_model := btrim(coalesce(payload->>'device_model',''));
  v_type := btrim(coalesce(payload->>'part_type',''));
  v_quality := btrim(coalesce(payload->>'quality','New'));
  v_color := nullif(btrim(coalesce(payload->>'color','')), '');
  v_location := nullif(btrim(coalesce(payload->>'storage_location','')), '');
  v_supplier := nullif(btrim(coalesce(payload->>'supplier','')), '');
  v_notes := nullif(btrim(coalesce(payload->>'notes','')), '');

  if v_model = '' then raise exception 'Device model is required'; end if;
  if v_type = '' then raise exception 'Part type is required'; end if;
  if char_length(v_model) > 120 or char_length(v_type) > 120 then
    raise exception 'Device model or part type is too long';
  end if;
  if v_quality not in ('New','Original / OEM','Original Pull','Aftermarket','Used') then
    raise exception 'Invalid part quality';
  end if;
  if coalesce(payload->>'quantity','') !~ '^[0-9]+$' then
    raise exception 'Quantity must be a whole number';
  end if;
  v_quantity := (payload->>'quantity')::integer;
  if v_quantity < 0 or v_quantity > 9999 then
    raise exception 'Quantity must be between 0 and 9999';
  end if;

  if part_id is not null then
    select * into existing
    from public.spare_parts
    where id::text = part_id
    for update;
    if not found then raise exception 'Part no longer exists. Refresh the list.'; end if;
  end if;

  if (a->>'can_view_financials')::boolean then
    if coalesce(payload->>'unit_cost','') = '' then
      v_unit_cost := 0;
    elsif (payload->>'unit_cost') !~ '^[0-9]+([.][0-9]+)?$' then
      raise exception 'Unit cost must be a nonnegative number';
    else
      v_unit_cost := (payload->>'unit_cost')::numeric;
    end if;
  else
    v_unit_cost := case when existing.id is not null then existing.unit_cost else 0 end;
  end if;

  if part_id is null then
    insert into public.spare_parts(
      device_model, part_type, quality, color, quantity, unit_cost,
      storage_location, supplier, notes, created_by
    )
    values(
      v_model, v_type, v_quality, v_color, v_quantity, v_unit_cost,
      v_location, v_supplier, v_notes, auth.uid()
    );
  else
    update public.spare_parts
    set device_model=v_model,
        part_type=v_type,
        quality=v_quality,
        color=v_color,
        quantity=v_quantity,
        unit_cost=v_unit_cost,
        storage_location=v_location,
        supplier=v_supplier,
        notes=v_notes,
        updated_at=now()
    where id=existing.id;
  end if;
end
$$;

create or replace function public.lager_delete_part(part_id text)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare
  a jsonb:=public.lager_access();
  n integer;
begin
  if not (a->>'can_delete')::boolean then
    raise exception 'Deletion is restricted' using errcode='42501';
  end if;

  delete from public.spare_parts where id::text=part_id;
  get diagnostics n=row_count;
  if n<>1 then raise exception 'Part no longer exists'; end if;
end
$$;

revoke all on function public.lager_parts() from public, anon, authenticated;
revoke all on function public.lager_save_part(text,jsonb) from public, anon, authenticated;
revoke all on function public.lager_delete_part(text) from public, anon, authenticated;
grant execute on function public.lager_parts() to authenticated;
grant execute on function public.lager_save_part(text,jsonb) to authenticated;
grant execute on function public.lager_delete_part(text) to authenticated;

create or replace function private.lager_snapshot_internal(snapshot_actor uuid default null)
returns bigint
language plpgsql
security definer
set search_path=''
as $$
declare new_id bigint;
begin
  insert into public.lager_cloud_snapshots(snapshot_date, created_by, data)
  values (
    current_date,
    snapshot_actor,
    jsonb_build_object(
      'version', 2,
      'created_at', now(),
      'phones', coalesce((select jsonb_agg(to_jsonb(p) order by p.id) from public.phones p), '[]'::jsonb),
      'spare_parts', coalesce((select jsonb_agg(to_jsonb(sp) order by sp.id) from public.spare_parts sp), '[]'::jsonb),
      'sale_history', coalesce((select jsonb_agg(to_jsonb(s) order by s.id) from public.lager_sale_history s), '[]'::jsonb),
      'market_prices', coalesce((select jsonb_agg(to_jsonb(m) order by m.id) from public.market_prices m), '[]'::jsonb)
    )
  )
  on conflict (snapshot_date) do update
  set created_at=excluded.created_at, created_by=excluded.created_by, data=excluded.data
  returning id into new_id;

  delete from public.lager_cloud_snapshots
  where snapshot_date < current_date - 60;

  return new_id;
end
$$;

notify pgrst,'reload schema';
